import type { Question, Subject, Topic } from "./types";

export const SUBJECTS: Subject[] = [
  {
    id: "mathematics",
    name: "Matematika",
    description: "Algebra, geometriya va mantiqiy masalalar.",
    color: "brand",
    examWeight: 40,
    position: 1,
  },
  {
    id: "uzbek",
    name: "Ona tili",
    description: "Imlo, uslubiyat va matn bilan ishlash.",
    color: "accent",
    examWeight: 25,
    position: 2,
  },
  {
    id: "english",
    name: "Ingliz tili",
    description: "Grammar, vocabulary va reading comprehension.",
    color: "violet",
    examWeight: 20,
    position: 3,
  },
];

export const TOPICS: Topic[] = [
  {
    id: "linear-equations",
    subjectId: "mathematics",
    name: "Chiziqli tenglamalar",
    description: "Bir noma'lumli tenglamalar va matnli masalalar.",
    level: "easy",
    estimatedMinutes: 15,
    position: 1,
  },
  {
    id: "quadratic-basics",
    subjectId: "mathematics",
    name: "Kvadrat tenglama",
    description: "Diskriminant, ildizlar va koeffitsiyentlar.",
    level: "medium",
    estimatedMinutes: 20,
    position: 2,
  },
  {
    id: "triangles",
    subjectId: "mathematics",
    name: "Uchburchaklar",
    description: "Burchaklar, perimetr va yuzaga oid savollar.",
    level: "medium",
    estimatedMinutes: 18,
    position: 3,
  },
  {
    id: "spelling",
    subjectId: "uzbek",
    name: "Imlo qoidalari",
    description: "Qo'shma va ajratib yoziladigan so'zlar.",
    level: "easy",
    estimatedMinutes: 12,
    position: 1,
  },
  {
    id: "text-analysis",
    subjectId: "uzbek",
    name: "Matn tahlili",
    description: "Asosiy fikr, dalil va xulosa bilan ishlash.",
    level: "medium",
    estimatedMinutes: 16,
    position: 2,
  },
  {
    id: "english-tenses",
    subjectId: "english",
    name: "English tenses",
    description: "Present, past va future zamonlar.",
    level: "easy",
    estimatedMinutes: 14,
    position: 1,
  },
  {
    id: "reading-main-idea",
    subjectId: "english",
    name: "Reading: main idea",
    description: "Matndagi asosiy fikr va kontekstni topish.",
    level: "medium",
    estimatedMinutes: 18,
    position: 2,
  },
];

export const QUESTIONS: Question[] = [
  {
    id: "q-linear-1",
    subjectId: "mathematics",
    topicId: "linear-equations",
    prompt: "3x + 7 = 22 tenglamani yeching.",
    options: ["x = 3", "x = 5", "x = 7", "x = 9"],
    correctIndex: 1,
    explanation: "3x = 22 - 7 = 15, demak x = 5.",
    difficulty: "easy",
  },
  {
    id: "q-linear-2",
    subjectId: "mathematics",
    topicId: "linear-equations",
    prompt: "2(x - 4) = 18 bo'lsa, x nechaga teng?",
    options: ["9", "11", "13", "15"],
    correctIndex: 2,
    explanation: "2x - 8 = 18, 2x = 26, x = 13.",
    difficulty: "easy",
  },
  {
    id: "q-linear-3",
    subjectId: "mathematics",
    topicId: "linear-equations",
    prompt: "Ali bir son o'yladi. Sonning 4 baravaridan 6 ayirilsa 30 chiqadi. Sonni toping.",
    options: ["6", "8", "9", "12"],
    correctIndex: 2,
    explanation: "4x - 6 = 30, 4x = 36, x = 9.",
    difficulty: "medium",
  },
  {
    id: "q-quad-1",
    subjectId: "mathematics",
    topicId: "quadratic-basics",
    prompt: "x^2 - 5x + 6 = 0 tenglamaning ildizlari qaysi?",
    options: ["1 va 6", "2 va 3", "-2 va -3", "0 va 5"],
    correctIndex: 1,
    explanation: "2 va 3 sonlarining yig'indisi 5, ko'paytmasi 6.",
    difficulty: "medium",
  },
  {
    id: "q-quad-2",
    subjectId: "mathematics",
    topicId: "quadratic-basics",
    prompt: "x^2 - 9 = 0 tenglama uchun x qiymatlari qaysi?",
    options: ["0 va 9", "-9 va 9", "-3 va 3", "3 va 9"],
    correctIndex: 2,
    explanation: "x^2 = 9, shuning uchun x = -3 yoki x = 3.",
    difficulty: "easy",
  },
  {
    id: "q-triangle-1",
    subjectId: "mathematics",
    topicId: "triangles",
    prompt: "Uchburchak burchaklari yig'indisi nechaga teng?",
    options: ["90°", "120°", "180°", "360°"],
    correctIndex: 2,
    explanation: "Har qanday uchburchak ichki burchaklari yig'indisi 180°.",
    difficulty: "easy",
  },
  {
    id: "q-triangle-2",
    subjectId: "mathematics",
    topicId: "triangles",
    prompt: "Tomonlari 5, 5 va 6 bo'lgan uchburchak qanday turga kiradi?",
    options: ["Teng tomonli", "Teng yonli", "To'g'ri burchakli", "Mavjud emas"],
    correctIndex: 1,
    explanation: "Ikki tomoni teng bo'lgani uchun bu teng yonli uchburchak.",
    difficulty: "easy",
  },
  {
    id: "q-spelling-1",
    subjectId: "uzbek",
    topicId: "spelling",
    prompt: "Qaysi so'z to'g'ri yozilgan?",
    options: ["xohlagan", "hohlagan", "xoxlagan", "hoh-lagan"],
    correctIndex: 0,
    explanation: "Adabiy imlo bo'yicha to'g'ri shakl: xohlagan.",
    difficulty: "easy",
  },
  {
    id: "q-spelling-2",
    subjectId: "uzbek",
    topicId: "spelling",
    prompt: "Qaysi birikma qo'shib yoziladi?",
    options: ["har doim", "bir oz", "allaqachon", "shu bilan"],
    correctIndex: 2,
    explanation: "'Allaqachon' ravishi qo'shib yoziladi.",
    difficulty: "medium",
  },
  {
    id: "q-text-1",
    subjectId: "uzbek",
    topicId: "text-analysis",
    prompt: "Matnning asosiy fikri deganda nima tushuniladi?",
    options: [
      "Eng uzun gap",
      "Muallif yetkazmoqchi bo'lgan bosh mazmun",
      "Birinchi jumla",
      "Notanish so'zlar ro'yxati",
    ],
    correctIndex: 1,
    explanation: "Asosiy fikr matnning bosh mazmunini ifodalaydi.",
    difficulty: "easy",
  },
  {
    id: "q-text-2",
    subjectId: "uzbek",
    topicId: "text-analysis",
    prompt: "Dalilning vazifasi qaysi?",
    options: [
      "Fikrni bezash",
      "Xulosani yashirish",
      "Fikrni asoslash",
      "Matnni qisqartirish",
    ],
    correctIndex: 2,
    explanation: "Dalil keltirilgan fikrni isbotlash yoki asoslash uchun ishlatiladi.",
    difficulty: "medium",
  },
  {
    id: "q-tense-1",
    subjectId: "english",
    topicId: "english-tenses",
    prompt: "Choose the correct sentence.",
    options: [
      "She go to school every day.",
      "She goes to school every day.",
      "She going to school every day.",
      "She gone to school every day.",
    ],
    correctIndex: 1,
    explanation: "With he/she/it in Present Simple, the verb takes -s: goes.",
    difficulty: "easy",
  },
  {
    id: "q-tense-2",
    subjectId: "english",
    topicId: "english-tenses",
    prompt: "I ____ my homework yesterday.",
    options: ["do", "does", "did", "doing"],
    correctIndex: 2,
    explanation: "Yesterday signals Past Simple, so the correct verb is did.",
    difficulty: "easy",
  },
  {
    id: "q-reading-1",
    subjectId: "english",
    topicId: "reading-main-idea",
    prompt: "In reading tasks, 'main idea' usually means:",
    options: [
      "The longest word in the text",
      "The writer's central message",
      "The final punctuation mark",
      "A random example",
    ],
    correctIndex: 1,
    explanation: "The main idea is the central message or point of the text.",
    difficulty: "easy",
  },
  {
    id: "q-reading-2",
    subjectId: "english",
    topicId: "reading-main-idea",
    prompt: "Which question helps find the main idea?",
    options: [
      "What is this text mostly about?",
      "How many commas are there?",
      "Which word is shortest?",
      "Who printed the page?",
    ],
    correctIndex: 0,
    explanation: "Asking what the text is mostly about points to the main idea.",
    difficulty: "medium",
  },
];

export function publicQuestion(question: Question) {
  return {
    id: question.id,
    subjectId: question.subjectId,
    topicId: question.topicId,
    prompt: question.prompt,
    options: question.options,
    difficulty: question.difficulty,
  };
}
